name: library/caddy

on:
  push:
    branches:
      - main
    paths:
      - "caddy/Dockerfile"
      - ".github/workflows/caddy.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: caddy
          tags: ghcr.io/mpfmedical/library/caddy:latest
          platforms: linux/amd64,linux/arm64
          push: true
